#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-software
Version  : 3.34.2
Release  : 47
URL      : https://download.gnome.org/sources/gnome-software/3.34/gnome-software-3.34.2.tar.xz
Source0  : https://download.gnome.org/sources/gnome-software/3.34/gnome-software-3.34.2.tar.xz
Source1  : http://localhost/cgit/projects/clr-software-icons/snapshot/clr-software-icons-1.tar.gz
Summary  : GNOME Software is a software center for GNOME
Group    : Development/Tools
License  : GPL-2.0
Requires: gnome-software-bin = %{version}-%{release}
Requires: gnome-software-data = %{version}-%{release}
Requires: gnome-software-lib = %{version}-%{release}
Requires: gnome-software-libexec = %{version}-%{release}
Requires: gnome-software-license = %{version}-%{release}
Requires: gnome-software-locales = %{version}-%{release}
Requires: gnome-software-man = %{version}-%{release}
Requires: clr-bundle-icons
Requires: clr-bundle-screenshots
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : clr-bundle-icons
BuildRequires : clr-bundle-screenshots
BuildRequires : docbook-xml
BuildRequires : gnome-online-accounts-dev
BuildRequires : gtk-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(appstream-glib)
BuildRequires : pkgconfig(flatpak)
BuildRequires : pkgconfig(fwupd)
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(gspell-1)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(packagekit-glib2)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(xmlb)
BuildRequires : source-highlight
BuildRequires : valgrind-dev
BuildRequires : zstd-dev
Patch1: 0001-gnome-software-implementation-for-swupd-and-clearlin.patch

%description
[![Build Status](https://gitlab.gnome.org/GNOME/gnome-software/badges/master/build.svg)](https://gitlab.gnome.org/GNOME/gnome-software/pipelines)

%package bin
Summary: bin components for the gnome-software package.
Group: Binaries
Requires: gnome-software-data = %{version}-%{release}
Requires: gnome-software-libexec = %{version}-%{release}
Requires: gnome-software-license = %{version}-%{release}

%description bin
bin components for the gnome-software package.


%package data
Summary: data components for the gnome-software package.
Group: Data

%description data
data components for the gnome-software package.


%package dev
Summary: dev components for the gnome-software package.
Group: Development
Requires: gnome-software-lib = %{version}-%{release}
Requires: gnome-software-bin = %{version}-%{release}
Requires: gnome-software-data = %{version}-%{release}
Provides: gnome-software-devel = %{version}-%{release}
Requires: gnome-software = %{version}-%{release}

%description dev
dev components for the gnome-software package.


%package doc
Summary: doc components for the gnome-software package.
Group: Documentation
Requires: gnome-software-man = %{version}-%{release}

%description doc
doc components for the gnome-software package.


%package lib
Summary: lib components for the gnome-software package.
Group: Libraries
Requires: gnome-software-data = %{version}-%{release}
Requires: gnome-software-libexec = %{version}-%{release}
Requires: gnome-software-license = %{version}-%{release}

%description lib
lib components for the gnome-software package.


%package libexec
Summary: libexec components for the gnome-software package.
Group: Default
Requires: gnome-software-license = %{version}-%{release}

%description libexec
libexec components for the gnome-software package.


%package license
Summary: license components for the gnome-software package.
Group: Default

%description license
license components for the gnome-software package.


%package locales
Summary: locales components for the gnome-software package.
Group: Default

%description locales
locales components for the gnome-software package.


%package man
Summary: man components for the gnome-software package.
Group: Default

%description man
man components for the gnome-software package.


%prep
%setup -q -n gnome-software-3.34.2
cd %{_builddir}
tar xf %{_sourcedir}/clr-software-icons-1.tar.gz
cd %{_builddir}/gnome-software-3.34.2
mkdir -p clearlinux
cp -r %{_builddir}/clr-software-icons-1/* %{_builddir}/gnome-software-3.34.2/clearlinux
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1574699339
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Denable-packagekit=false -Denable-ubuntuone=false -Denable-ubuntu-reviews=false -Denable-snap=false -Denable-gtk-doc=false  -Dpackagekit=false -Dfwupd=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-software
cp %{_builddir}/gnome-software-3.34.2/COPYING %{buildroot}/usr/share/package-licenses/gnome-software/4cc77b90af91e615a64ae04893fdffa7939db84c
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-software
## install_append content
install -m 0644 clearlinux/data/icons/hicolor/scalable/org.clearlinux.Software.svg %{buildroot}/usr/share/icons/hicolor/scalable/apps/org.gnome.Software.svg
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-software
/usr/bin/gnome-software-editor

%files data
%defattr(-,root,root,-)
/usr/share/app-info/xmls/org.gnome.Software.Featured.xml
/usr/share/applications/gnome-software-local-file.desktop
/usr/share/applications/org.gnome.Software.Editor.desktop
/usr/share/applications/org.gnome.Software.desktop
/usr/share/dbus-1/services/org.gnome.Software.service
/usr/share/glib-2.0/schemas/org.gnome.software.gschema.xml
/usr/share/gnome-shell/search-providers/org.gnome.Software-search-provider.ini
/usr/share/gnome-software/featured-FeedReader.svg
/usr/share/gnome-software/featured-bitwarden.svg
/usr/share/gnome-software/featured-boxes.svg
/usr/share/gnome-software/featured-calibre-bg.jpg
/usr/share/gnome-software/featured-darktable-bg.jpg
/usr/share/gnome-software/featured-dropbox.png
/usr/share/gnome-software/featured-foliate.svg
/usr/share/gnome-software/featured-fondo-bg.jpg
/usr/share/gnome-software/featured-gimp.png
/usr/share/gnome-software/featured-gnome-sudoku.png
/usr/share/gnome-software/featured-homebank-bg.jpg
/usr/share/gnome-software/featured-inkscape.svg
/usr/share/gnome-software/featured-kdenlive-bg.jpg
/usr/share/gnome-software/featured-klavaro-bg.jpg
/usr/share/gnome-software/featured-maps-bg.png
/usr/share/gnome-software/featured-maps.svg
/usr/share/gnome-software/featured-marker-bg.jpg
/usr/share/gnome-software/featured-mypaint.svg
/usr/share/gnome-software/featured-pdf-slicer.svg
/usr/share/gnome-software/featured-podcasts.svg
/usr/share/gnome-software/featured-polari.svg
/usr/share/gnome-software/featured-slack-bg.jpg
/usr/share/gnome-software/featured-sound-recorder.svg
/usr/share/gnome-software/featured-stellarium-bg.jpg
/usr/share/gnome-software/featured-tetravex-bg.jpg
/usr/share/gnome-software/featured-todo-bg.jpg
/usr/share/gnome-software/featured-transmission.svg
/usr/share/gnome-software/featured-uberwriter.svg
/usr/share/gnome-software/featured-vlc-bg.jpg
/usr/share/gnome-software/upgrade-bg.png
/usr/share/icons/hicolor/scalable/apps/org.gnome.Software.svg
/usr/share/icons/hicolor/scalable/status/software-installed-symbolic.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Software-symbolic.svg
/usr/share/metainfo/org.gnome.Software.Plugin.Epiphany.metainfo.xml
/usr/share/metainfo/org.gnome.Software.Plugin.Flatpak.metainfo.xml
/usr/share/metainfo/org.gnome.Software.Plugin.Odrs.metainfo.xml
/usr/share/metainfo/org.gnome.Software.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/gnome-software/gnome-software.h
/usr/include/gnome-software/gs-app-list.h
/usr/include/gnome-software/gs-app.h
/usr/include/gnome-software/gs-category.h
/usr/include/gnome-software/gs-metered.h
/usr/include/gnome-software/gs-os-release.h
/usr/include/gnome-software/gs-plugin-event.h
/usr/include/gnome-software/gs-plugin-types.h
/usr/include/gnome-software/gs-plugin-vfuncs.h
/usr/include/gnome-software/gs-plugin.h
/usr/include/gnome-software/gs-utils.h
/usr/lib64/pkgconfig/gnome-software.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/gnome\-software/*
/usr/share/gtk-doc/html/gnome-software/api.html
/usr/share/gtk-doc/html/gnome-software/gnome-software-GsApp.html
/usr/share/gtk-doc/html/gnome-software/gnome-software-GsAppList.html
/usr/share/gtk-doc/html/gnome-software/gnome-software-GsOsRelease.html
/usr/share/gtk-doc/html/gnome-software/gnome-software-GsPlugin-Exports.html
/usr/share/gtk-doc/html/gnome-software/gnome-software-GsPlugin.html
/usr/share/gtk-doc/html/gnome-software/gnome-software-GsPluginEvent.html
/usr/share/gtk-doc/html/gnome-software/gnome-software-GsUtils.html
/usr/share/gtk-doc/html/gnome-software/gnome-software-gs-category.html
/usr/share/gtk-doc/html/gnome-software/gnome-software.devhelp2
/usr/share/gtk-doc/html/gnome-software/gs-example-details.png
/usr/share/gtk-doc/html/gnome-software/gs-example-installed.png
/usr/share/gtk-doc/html/gnome-software/gs-example-search.png
/usr/share/gtk-doc/html/gnome-software/home.png
/usr/share/gtk-doc/html/gnome-software/index.html
/usr/share/gtk-doc/html/gnome-software/left-insensitive.png
/usr/share/gtk-doc/html/gnome-software/left.png
/usr/share/gtk-doc/html/gnome-software/right-insensitive.png
/usr/share/gtk-doc/html/gnome-software/right.png
/usr/share/gtk-doc/html/gnome-software/style.css
/usr/share/gtk-doc/html/gnome-software/tutorial.html
/usr/share/gtk-doc/html/gnome-software/up-insensitive.png
/usr/share/gtk-doc/html/gnome-software/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/gs-plugins-13/libgs_plugin_appstream.so
/usr/lib64/gs-plugins-13/libgs_plugin_desktop-categories.so
/usr/lib64/gs-plugins-13/libgs_plugin_desktop-menu-path.so
/usr/lib64/gs-plugins-13/libgs_plugin_dpkg.so
/usr/lib64/gs-plugins-13/libgs_plugin_dummy.so
/usr/lib64/gs-plugins-13/libgs_plugin_epiphany.so
/usr/lib64/gs-plugins-13/libgs_plugin_fedora-pkgdb-collections.so
/usr/lib64/gs-plugins-13/libgs_plugin_fedora_langpacks.so
/usr/lib64/gs-plugins-13/libgs_plugin_flatpak.so
/usr/lib64/gs-plugins-13/libgs_plugin_generic-updates.so
/usr/lib64/gs-plugins-13/libgs_plugin_hardcoded-blacklist.so
/usr/lib64/gs-plugins-13/libgs_plugin_hardcoded-featured.so
/usr/lib64/gs-plugins-13/libgs_plugin_hardcoded-popular.so
/usr/lib64/gs-plugins-13/libgs_plugin_icons.so
/usr/lib64/gs-plugins-13/libgs_plugin_key-colors-metadata.so
/usr/lib64/gs-plugins-13/libgs_plugin_key-colors.so
/usr/lib64/gs-plugins-13/libgs_plugin_modalias.so
/usr/lib64/gs-plugins-13/libgs_plugin_odrs.so
/usr/lib64/gs-plugins-13/libgs_plugin_os-release.so
/usr/lib64/gs-plugins-13/libgs_plugin_provenance-license.so
/usr/lib64/gs-plugins-13/libgs_plugin_provenance.so
/usr/lib64/gs-plugins-13/libgs_plugin_repos.so
/usr/lib64/gs-plugins-13/libgs_plugin_rewrite-resource.so
/usr/lib64/gs-plugins-13/libgs_plugin_shell-extensions.so
/usr/lib64/gs-plugins-13/libgs_plugin_swupd.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gnome-software-cmd
/usr/libexec/gnome-software-restarter

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-software/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gnome-software-editor.1
/usr/share/man/man1/gnome-software.1

%files locales -f gnome-software.lang
%defattr(-,root,root,-)

